= subprocessj

== What is this?

1. You can execute arbitrary OS command from your Java application
 using `com.kazurayam.subprocessj.Subprocess`.
 This class utilizes `java.lang.ProcessBuilder`.
 A new OS process will be started and run background.
2. You can find the process id of the process which is listening to a specific IP port of the localhost
 using `com.kazurayam.subprocessj.ProcessFinder`.
 It can find the pid of current JVM process as well.
3. You can stop a server process by pid or by the IP port
 using `com.kazurayam.subprocessj.ProcessTerminator`.
4. You can find the absolute file path of commands
 using `com.kazurayam.subprocesj.CommandFinder`.
5. You can find the type of OS on which your java application is
 currently working using `com.kazurayam.subprocessj.OSType`.

== Motivation

There are many articles that tell how to use https://docs.oracle.com/javase/8/docs/api/java/lang/ProcessBuilder.html[`java.lang.ProcessBuilder`]. For example, I learned https://www.baeldung.com/run-shell-command-in-java["Baeldung article: Run Shell Command in Java"]. The ProcessBuilder class is a state of the art with rich set of functionalities. But it is not easy for me to write a program that utilized ProcessBuilder. It involves multi-threading to consume the output streams (STDOUT and STDERR) from subprocess. I do not want to repeat writing it.

So I have made a simple wrapper of ProcessBuilder which exposes a limited subset of its functionalities.

I named this as `subprocessj` as I meant it to be a homage to the https://docs.python.org/3/library/subprocess.html[Subprocess] module of Python.

I wanted to use `Subprocess` to start and stop an HTTP server inside
a JUnit test for my Java application.
I wanted to start Python-based HTTP server using the `docker run` command.
Then I need to be able to kill the background process.
I wanted this procedure fully automated.
In order to achieve this, I developed `ProcessTerminator` and some helpers.

== API

Javadoc is https://kazurayam.github.io/subprocessj/api/index.html[here].

== Example of using Subprocess classes

=== Starting a process

You just call `com.kazurayam.subprocessj.Subprocess.run(List<String> command)`. The `run()` will wait for the sub-process to finish, and returns a `com.kazurayam.subprocessj.CompletedProcess` object which contains the return code, STDOUT and STDERR emitted by the sub-process.

[source, java]
----
include::../src/test/java/com/kazurayam/subprocessj/SubprocessTest.java[]
----

This will emit the following output in the console:

----
0
total 4712
drwxr-xr-x+  90 kazurayam       staff     2880  7 31 21:01 .
drwxr-xr-x    6 root            admin      192  1  1  2020 ..
...
----

=== Stopping a process

Using `java.lang.ProcessBuilder` class, you can create a `java.lang.Process` in which arbitrary application can run. Suppose you created a process in which HTTP Server runs. The process will stay running long until you explicitly stop it. But how can you stop that process?

Sometimes I encounter a new HTTP Server fails to start because the IP port is already in use. It tends to happen because I am not careful enough to stop the previous server process which is hanging on the IP port. In such situation, I have to do, on Mac, the following operations:

1. execute a shell command `$ lsof -i:<port> -P`, to find out the id of the process which is still hanging on the IP port.
2. execute a shell command `$ kill <processId>`, to stop the process.
3. once the process is stopped, the IP port is released.

I wanted to automate this command line operation in my Java code. So I developed a Java class link:../src/main/java/com/kazurayam/subprocessj/ProcessTerminator.java[`com.kazurayam.subprocessj.ProcessTerminator`].

See the following sample JUnit 5 test to see how to use the ProcessKiller.

[source, java]
----
include::../src/test/java/com/kazurayam/subprocessj/HiThereServerAsProcessTest.java[]
----

@BeforeAll-annotated method starts the link:../src/main/java/com/kazurayam/subprocessj/HiThereServer.java[HiThereServer] using `ProcessBuilder`. The process will start and stay running background. The HiThereServer is a simple HTTP server, listens to the IP port 8500.

@Test-annotated method makes an HTTP request to the HiThereServer.

@AfterAll-annotated method shuts down the HiThereServer using the `ProcessTerminator`. You specify the IP port 8500. The ProcessKiller will find the process ID of a process which is listening the port 8500, and kill the process.

=== Finding the path of an OS command

[source,java]
----
include::../src/test/java/com/kazurayam/subprocessj/CommandLocatorTest.java[]
----

=== Finding process id

==== Finding the pid of the current JVM

[source,java]
----
include::../src/test/java/com/kazurayam/subprocessj/ProcessFinderTest_CurrentJvmPid.java[]
----

==== Finding the pid of a process which is listening to a specific IP port

[source,java]
----
include::../src/test/java/com/kazurayam/subprocessj/ProcessFinderTest_base.java[]
----

=== Identifying OS Type

[source,java]
----
include::../src/test/java/com/kazurayam/subprocessj/OSTypeTest.java[]
----

=== retrieving Password from Mac KeyChain

I often write Selenium test that access to some Web apps with authentication.
I need to put username/password pair. Due to obvious security reason,
I do not like to write password strings in the source code at all.
I would rather like to use the link:https://support.apple.com/guide/keychain-access/kyca1083/mac[KeyChain] of macOS
to store passwords, and I want my Selenium test to retrieve the password from KeyChain.

KeyChain provides a commandline interface named `security` which is built-in the macOS.
So I want my Selenium test to execute the `security` command and
retrieve the password value I need.

The following sample shows how to.

[src,java]
----
include::../src/test/java/example/KeyChainExample.java[]
----

== Running a javascript on Node.js from Java

I have a javascript `hello.js`, which is (as you can correctly expect):

[source, javascript]
----
console.log("Hello, World!");
----

The following JUnit5 test runs Node.js in command line while specifying the `hello.js` to execute:

[source, java]
----
include::../src/test/java/com/kazurayam/subprocessj/NodejsTest.java[]
----


== A sample code to run a utility "pngquant" from Java

The following JUnit5 test shows a sample how to invoke link:https://pngquant.org/[pngquant] to compress a PNG image file.

[source, java]
----
include::../src/test/java/com/kazurayam/subprocessj/PngquantTest.java[]
----

The output from this test is as follows:
[source]
----
[test_compress_png_using_pngquant]
<completed-process rc="0">
<command>pngquant --ext .png --force --speed 1 ./build/tmp/testOutput/PngquantTest/apple.png</command>
<stdout>
</stdout>
<stderr>
</stdout>
</completed-process>

file: ./build/tmp/testOutput/PngquantTest/apple.png
size before compression: 3655
size after compression: 2818
size delta: Δ22%
----

== How to get Environment Variable values

[source, java]
----
include::../src/test/java/com/kazurayam/subprocessj/EchoPathTest.java[]
----

When I executed, I got the following output
[source, text]
----
PATH: /bin:/sbin:/usr/bin:/usr/local/bin:/usr/local/bin:/usr/local/go/bin:/usr/local/sbin:/usr/sbin:/Users/kazuakiurayama/.nodebrew/current/bin: ... and a lot more
----

== How to get the Git current branch name

[source, java]
----
include::../src/test/java/example/GitCommandExample.java[]
----

When I ran this test, I got the following output in the console:

[source,text]
----
> Task :compileJava UP-TO-DATE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :compileTestJava UP-TO-DATE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :test
current GIT branch: issue38
/usr/local/bin/git
> Task :jacocoTestReport
BUILD SUCCESSFUL in 3s
4 actionable tasks: 2 executed, 2 up-to-date
9:29:50: Execution finished ':test --tests "example.GitCommandExample"'.
----




== links

The artifact is available at the Maven Central repository:

* link:https://mvnrepository.com/artifact/com.kazurayam/subprocessj[https://mvnrepository.com/artifact/com.kazurayam/subprocessj]

The project's repository is here

* https://github.com/kazurayam/subprocessj/[the repository]
